"""
Config for constand values across the app
"""
# CAMERA_WIDTH = 640
# CAMERA_HEIGHT = 480
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720
# CAMERA_WIDTH = 1920
# CAMERA_HEIGHT = 1080
CAMERA_RESOLUTION = (CAMERA_WIDTH, CAMERA_HEIGHT)
COMPARE_FACES_COOLDOWN = 5
FACE_TRACKING_COOLDOWN = 1.6
MAX_FACE_SIZE = 60000

YAW_MAX = 90 # Maybe need to cut this in half
PITCH_MAX = 27